{
 "title": "Vogorode metrics Copy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "[Landscape] Average endpoint execution time in ms",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "GET /users/types",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 1 },
     "targets": [
      {
       "expr": "increase(dev_archie_landscapeservice_user_UserController_getUserTypes_seconds_sum[1m]) / increase(dev_archie_landscapeservice_user_UserController_getUserTypes_seconds_count[1m])",
       "legendFormat": "{{instance}} {{exception}}"
      }
     ]
    },
    {
     "title": "DELETE /users",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "increase(dev_archie_landscapeservice_user_UserController_delete_seconds_sum[1m]) / increase(dev_archie_landscapeservice_user_UserController_delete_seconds_count[1m])",
       "legendFormat": "{{instance}} {{exception}}"
      }
     ]
    },
    {
     "title": "POST /users",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "increase(dev_archie_landscapeservice_user_UserController_create_seconds_sum[1m]) / increase(dev_archie_landscapeservice_user_UserController_create_seconds_count[1m])",
       "legendFormat": "{{instance}} {{exception}}"
      }
     ]
    },
    {
     "title": "GET /users",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "increase(dev_archie_landscapeservice_user_UserController_getById_seconds_sum[1m]) / increase(dev_archie_landscapeservice_user_UserController_getById_seconds_count[1m])",
       "legendFormat": "{{instance}} {{exception}}"
      }
     ]
    },
    {
     "title": "PUT /users",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "increase(dev_archie_landscapeservice_user_UserController_update_seconds_sum[1m]) / increase(dev_archie_landscapeservice_user_UserController_update_seconds_count[1m])",
       "legendFormat": "{{instance}} {{exception}}"
      }
     ]
    }
   ]
  },
  {
   "title": "[Rancher] Average endpoint execution time in ms",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "POST /ranchers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "increase(dev_archie_rancherservice_rancher_RancherController_create_seconds_sum[1m]) / increase(dev_archie_rancherservice_rancher_RancherController_create_seconds_count[1m])",
       "legendFormat": "{{instance}} {{exception}}"
      }
     ]
    },
    {
     "title": "DELETE /ranchers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "increase(dev_archie_rancherservice_rancher_RancherController_delete_seconds_sum[1m]) / increase(dev_archie_rancherservice_rancher_RancherController_delete_seconds_count[1m])",
       "legendFormat": "{{instance}} {{exception}}"
      }
     ]
    },
    {
     "title": "GET /ranchers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "increase(dev_archie_rancherservice_rancher_RancherController_getById_seconds_sum[1m]) / increase(dev_archie_rancherservice_rancher_RancherController_getById_seconds_count[1m])",
       "legendFormat": "{{instance}} {{exception}}"
      }
     ]
    },
    {
     "title": "PUT /ranchers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "increase(dev_archie_rancherservice_rancher_RancherController_update_seconds_sum[1m]) / increase(dev_archie_rancherservice_rancher_RancherController_update_seconds_count[1m])",
       "legendFormat": "{{instance}} {{exception}}"
      }
     ]
    }
   ]
  },
  {
   "title": "[Handyman] Average endpoint execution time in ms ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "POST /handymen",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "increase(dev_archie_handymanservice_handyman_HandymanController_update_seconds_sum[1m]) / increase(dev_archie_handymanservice_handyman_HandymanController_update_seconds_count[1m])",
       "legendFormat": "{{instance}} {{exception}}"
      }
     ]
    },
    {
     "title": "DELETE /handymen",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "increase(dev_archie_handymanservice_handyman_HandymanController_delete_seconds_sum[1m]) / increase(dev_archie_handymanservice_handyman_HandymanController_delete_seconds_count[1m])",
       "legendFormat": "{{instance}} {{exception}}"
      }
     ]
    },
    {
     "title": "GET /handymen",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "increase(dev_archie_handymanservice_handyman_HandymanController_getById_seconds_sum[1m]) / increase(dev_archie_handymanservice_handyman_HandymanController_getById_seconds_count[1m])",
       "legendFormat": "{{instance}} {{exception}}"
      }
     ]
    },
    {
     "title": "PUT /handymen",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "increase(dev_archie_handymanservice_handyman_HandymanController_update_seconds_sum[1m]) / increase(dev_archie_handymanservice_handyman_HandymanController_update_seconds_count[1m])",
       "legendFormat": "{{instance}} {{exception}}"
      }
     ]
    }
   ]
  },
  { "title": "System metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "JVM memory usage in MB",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by(instance) (jvm_memory_used_bytes) / 1024 / 1024",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System CPU in %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}