version: "3.9"

networks:
  app-tier:
    driver: bridge

services:
  handyman-service:
    container_name: handyman-service
    build: ../handyman-service
    ports:
      - "8080:8080"
      - "9090:9090"
    networks:
      - app-tier
    environment:
      - SERVICE_ADDRESS=0.0.0.0
      - MONGO_DB_URI=mongodb://mongo:27017/handyman
      - LANDSCAPE_REST_URL=http://landscape-service:8081/
    depends_on:
      - landscape-service
      - mongo

  landscape-service:
    container_name: landscape-service
    build: ../landscape-service
    ports:
      - "8081:8081"
    networks:
      - app-tier
    environment:
      - HANDYMAN_ADDRESS=static://handyman-service:9090
      - RANCHER_ADDRESS=static://rancher-service:9091
      - DB_URL=jdbc:postgresql://postgres:5432/postgres?currentSchema=public
      - DB_USERNAME=postgres
      - DB_PASSWORD=123
    depends_on:
      - postgres

  rancher-service:
    container_name: rancher-service
    build: ../rancher-service
    ports:
      - "8082:8082"
      - "9091:9091"
    networks:
      - app-tier
    environment:
      - SERVICE_ADDRESS=0.0.0.0
      - MONGO_DB_URI=mongodb://mongo:27017/rancher
      - LANDSCAPE_REST_URL=http://landscape-service:8081/
      - PG_DB_URL=jdbc:postgresql://postgres:5432/postgres?currentSchema=public
      - PG_DB_USERNAME=postgres
      - PG_DB_PASSWORD=123
    depends_on:
      - landscape-service
      - mongo

  postgres:
    image: postgis/postgis:15-3.3
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
    networks:
      - app-tier

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data/:/data/db
    networks:
      - app-tier

  mongo-express:
    image: mongo-express
    ports:
      - 8085:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    networks:
      - app-tier
    depends_on:
      - mongo

  prometheus:
    image: bitnami/prometheus:2.42.0
    container_name: prometheus
    ports:
      - "1000:1000"
    command:
      - --web.listen-address=:10000
      - --storage.tsdb.path=/prometheus
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/opt/bitnami/prometheus/data
    networks:
      - app-tier

  grafana:
    image: bitnami/grafana:9.4.3
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECUTIRY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana_data:/opt/bitnami/grafana/data
      - ../monitoring/grafana/provisioning:/opt/bitnami/grafana/conf/provisioning
    networks:
      - app-tier
    depends_on:
      - prometheus
