apiVersion: v1
kind: Service
metadata:
  name: landscape
  namespace: default
spec:
  selector:
    app: landscape
  type: LoadBalancer
  ports:
  - name: landscape-rest
    protocol: TCP
    port: 8081
    targetPort: landscape-rest
    nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  landscape
  namespace: default
  labels:
    app:  landscape
spec:
  selector:
    matchLabels:
      app: landscape
  replicas: 1
  template:
    metadata:
      labels:
        app:  landscape
    spec:
      initContainers:
      - name: init-wait
        image: alpine
        command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 postgres 5432 && exit 0 || sleep 3; done; exit 1"]
      containers:
      - name:  landscape
        image:  devarchie/landscape:latest
        imagePullPolicy: Always
        env:
        - name: HANDYMAN_ADDRESS
          value: static://handyman:9090
        - name: RANCHER_ADDRESS
          value: static://rancher:9091
        - name: DB_URL
          value: jdbc:postgresql://postgres:5432/postgres?currentSchema=public
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_PASSWORD
        livenessProbe:
          httpGet:
            path: /system/liveness
            port: 8081
          initialDelaySeconds: 100
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /system/readiness
            port: 8081
          initialDelaySeconds: 100
          periodSeconds: 3
        ports:
        - containerPort:  8081
          name:  landscape-rest
      restartPolicy: Always
