apiVersion: v1
kind: Service
metadata:
  name: landscape
  namespace: default
spec:
  selector:
    app: landscape
  type: LoadBalancer
  ports:
  - name: landscape-rest
    protocol: TCP
    port: 8081
    targetPort: landscape-rest
    nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  landscape
  namespace: default
  labels:
    app:  landscape
spec:
  selector:
    matchLabels:
      app: landscape
  replicas: 1
  template:
    metadata:
      labels:
        app:  landscape
    spec:
      containers:
      - name:  landscape
        image:  devarchie/landscape:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: HANDYMAN_ADDRESS
          value: static://handyman:9090
        - name: RANCHER_ADDRESS
          value: static://rancher:9091
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        livenessProbe:
          httpGet:
            path: /system/liveness
            port: 8081
          initialDelaySeconds: 40
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /system/readiness
            port: 8081
          initialDelaySeconds: 40
          periodSeconds: 3
        ports:
        - containerPort:  8081
          name:  landscape-rest
      restartPolicy: Always
