apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgre-pv
  namespace: default
spec:
  capacity:
    storage: 40Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /data/volumes/pv1/
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
